apiVersion: v1
kind: ConfigMap
metadata:
  name: trakt-toggl-config
  namespace: trakt-toggl
data:
  TRAKT_HISTORY_DAYS: "7"
  TOGGL_TAGS: "watching,entertainment"
  # Update these values for your setup
  TOGGL_WORKSPACE_ID: "YOUR_WORKSPACE_ID"
  TOGGL_PROJECT_ID: "YOUR_PROJECT_ID"
