apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trakt-tokens-pvc
  namespace: trakt-toggl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
  # Adjust storageClassName based on your cluster
  # Comment out or remove if using default storage class
  # storageClassName: standard
