apiVersion: v1
kind: Secret
metadata:
  name: trakt-tokens
  namespace: trakt-toggl
type: Opaque
data:
  # This file will be created automatically after first authentication
  # If you already have a .trakt_tokens.json file, you can create this secret with:
  # kubectl create secret generic trakt-tokens \
  #   --from-file=.trakt_tokens.json=.trakt_tokens.json \
  #   --namespace=trakt-toggl
  .trakt_tokens.json: ""
